// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibraryFolder(arg1) {
  return window['go']['app']['App']['AddLibraryFolder'](arg1);
}

export function AvailableSystems() {
  return window['go']['app']['App']['AvailableSystems']();
}

export function BrowseForLibraryFolder() {
  return window['go']['app']['App']['BrowseForLibraryFolder']();
}

export function GetArtwork(arg1) {
  return window['go']['app']['App']['GetArtwork'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['app']['App']['LaunchGame'](arg1);
}

export function LibraryFolders() {
  return window['go']['app']['App']['LibraryFolders']();
}

export function ListGames() {
  return window['go']['app']['App']['ListGames']();
}

export function ListSaveSlots() {
  return window['go']['app']['App']['ListSaveSlots']();
}

export function LoadState(arg1) {
  return window['go']['app']['App']['LoadState'](arg1);
}

export function LoadStateFromSlot(arg1) {
  return window['go']['app']['App']['LoadStateFromSlot'](arg1);
}

export function PauseGame() {
  return window['go']['app']['App']['PauseGame']();
}

export function RemoveGame(arg1) {
  return window['go']['app']['App']['RemoveGame'](arg1);
}

export function RemoveLibraryFolder(arg1) {
  return window['go']['app']['App']['RemoveLibraryFolder'](arg1);
}

export function RescanLibrary() {
  return window['go']['app']['App']['RescanLibrary']();
}

export function ResumeGame() {
  return window['go']['app']['App']['ResumeGame']();
}

export function SaveState() {
  return window['go']['app']['App']['SaveState']();
}

export function SaveStateToSlot(arg1) {
  return window['go']['app']['App']['SaveStateToSlot'](arg1);
}

export function SendInput(arg1) {
  return window['go']['app']['App']['SendInput'](arg1);
}

export function StopGame() {
  return window['go']['app']['App']['StopGame']();
}
