// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {game} from '../models';
import {app} from '../models';

export function AddLibraryFolder(arg1:string):Promise<number>;

export function AvailableSystems():Promise<Array<core.Metadata>>;

export function BrowseForLibraryFolder():Promise<string>;

export function GetArtwork(arg1:string):Promise<string>;

export function LaunchGame(arg1:string):Promise<void>;

export function LibraryFolders():Promise<Array<string>>;

export function ListGames():Promise<Array<game.Game>>;

export function ListSaveSlots():Promise<Array<app.SaveSlotInfo>>;

export function LoadState(arg1:string):Promise<void>;

export function LoadStateFromSlot(arg1:number):Promise<void>;

export function PauseGame():Promise<void>;

export function RemoveGame(arg1:string):Promise<void>;

export function RemoveLibraryFolder(arg1:string):Promise<void>;

export function RescanLibrary():Promise<number>;

export function ResumeGame():Promise<void>;

export function SaveState():Promise<string>;

export function SaveStateToSlot(arg1:number):Promise<void>;

export function SendInput(arg1:number):Promise<void>;

export function StopGame():Promise<void>;
