package cpu

// Load instructions: register/immediate/memory moves. The two big
// families (LD r,r' and LD r,d8) follow a regular bit pattern, so they're
// generated by loops instead of spelled out 64+8 times.
func init() {
	// 0x40-0x7F: LD r,r' for every combination of the 8 r8 slots, except
	// 0x76 which is HALT (registered separately in opcodes_control.go).
	for dst := byte(0); dst < 8; dst++ {
		for src := byte(0); src < 8; src++ {
			opcode := 0x40 + dst*8 + src
			if opcode == 0x76 {
				continue
			}
			d, s := dst, src
			cycles := 4
			if d == 6 || s == 6 {
				cycles = 8
			}
			mainTable[opcode] = func(c *CPU) int {
				c.writeR8(d, c.readR8(s))
				return cycles
			}
		}
	}

	// 0x06,0x0E,...,0x3E: LD r,d8
	for idx := byte(0); idx < 8; idx++ {
		opcode := 0x06 + idx*8
		i := idx
		cycles := 8
		if i == 6 {
			cycles = 12
		}
		mainTable[opcode] = func(c *CPU) int {
			c.writeR8(i, c.fetch8())
			return cycles
		}
	}

	// 0x01,0x11,0x21,0x31: LD rr,d16
	for idx := byte(0); idx < 4; idx++ {
		opcode := 0x01 + idx*0x10
		i := idx
		mainTable[opcode] = func(c *CPU) int {
			c.writeR16(i, c.fetch16())
			return 12
		}
	}

	// 0xC1/D1/E1/F1 POP rr, 0xC5/D5/E5/F5 PUSH rr
	for idx := byte(0); idx < 4; idx++ {
		i := idx
		mainTable[0xC1+i*0x10] = func(c *CPU) int {
			c.writeR16Stack(i, c.pop16())
			return 12
		}
		mainTable[0xC5+i*0x10] = func(c *CPU) int {
			c.push16(c.readR16Stack(i))
			return 16
		}
	}
}

func init() {
	mainTable[0x02] = func(c *CPU) int { c.bus.Write(c.regs.BC(), c.regs.A); return 8 }
	mainTable[0x12] = func(c *CPU) int { c.bus.Write(c.regs.DE(), c.regs.A); return 8 }
	mainTable[0x0A] = func(c *CPU) int { c.regs.A = c.bus.Read(c.regs.BC()); return 8 }
	mainTable[0x1A] = func(c *CPU) int { c.regs.A = c.bus.Read(c.regs.DE()); return 8 }

	mainTable[0x22] = func(c *CPU) int {
		hl := c.regs.HL()
		c.bus.Write(hl, c.regs.A)
		c.regs.SetHL(hl + 1)
		return 8
	}
	mainTable[0x32] = func(c *CPU) int {
		hl := c.regs.HL()
		c.bus.Write(hl, c.regs.A)
		c.regs.SetHL(hl - 1)
		return 8
	}
	mainTable[0x2A] = func(c *CPU) int {
		hl := c.regs.HL()
		c.regs.A = c.bus.Read(hl)
		c.regs.SetHL(hl + 1)
		return 8
	}
	mainTable[0x3A] = func(c *CPU) int {
		hl := c.regs.HL()
		c.regs.A = c.bus.Read(hl)
		c.regs.SetHL(hl - 1)
		return 8
	}

	mainTable[0x08] = func(c *CPU) int {
		addr := c.fetch16()
		c.bus.Write(addr, byte(c.regs.SP))
		c.bus.Write(addr+1, byte(c.regs.SP>>8))
		return 20
	}
	mainTable[0xF9] = func(c *CPU) int { c.regs.SP = c.regs.HL(); return 8 }
	mainTable[0xF8] = func(c *CPU) int {
		c.regs.SetHL(c.addSPSigned(int8(c.fetch8())))
		return 12
	}

	mainTable[0xEA] = func(c *CPU) int { c.bus.Write(c.fetch16(), c.regs.A); return 16 }
	mainTable[0xFA] = func(c *CPU) int { c.regs.A = c.bus.Read(c.fetch16()); return 16 }

	mainTable[0xE0] = func(c *CPU) int { c.bus.Write(0xFF00+uint16(c.fetch8()), c.regs.A); return 12 }
	mainTable[0xF0] = func(c *CPU) int { c.regs.A = c.bus.Read(0xFF00 + uint16(c.fetch8())); return 12 }
	mainTable[0xE2] = func(c *CPU) int { c.bus.Write(0xFF00+uint16(c.regs.C), c.regs.A); return 8 }
	mainTable[0xF2] = func(c *CPU) int { c.regs.A = c.bus.Read(0xFF00 + uint16(c.regs.C)); return 8 }
}
